services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  clinicalsapp:
    container_name: clinicalsapi
    restart: always
    build: .
    ports:
      - '80:8000'
    links:
      - mongo